name: Deploy ASP.NET Core App to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install dependencies
        run: dotnet restore azure-appservice/azure-appservice.csproj 

      - name: Build the project
        run: dotnet build azure-appservice/azure-appservice.csproj --configuration Release --no-restore  # Specify the project file

      - name: Publish the project
        run: dotnet publish azure-appservice/azure-appservice.csproj --configuration Release --output ./azure-appservice/publish --no-build 

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: azdm-prod-app01
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./azure-appservice/publish  

      - name: Set Azure App Service Environment Variables
        run: |
          az webapp config appsettings set --resource-group iric_dev2 --name azdm-prod-app01 --settings \
            AzureAd__Instance=${{ secrets.AZURE_AD_INSTANCE }} \
            AzureAd__Domain=${{ secrets.AZURE_AD_DOMAIN }} \
            AzureAd__TenantId=${{ secrets.AZURE_AD_TENANT_ID }} \
            AzureAd__ClientId=${{ secrets.AZURE_AD_CLIENT_ID }} \
            AzureAd__ClientSecret=${{ secrets.AZURE_AD_CLIENT_SECRET }} \
            ServiceBusConnectionString=${{ secrets.SERVICE_BUS_CONNECTION_STRING }} \
            ServiceBusTopicName=${{ secrets.SERVICE_BUS_TOPIC_NAME }}
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
